export const Icons = [
  'AiFillHeart',
  'AiFillPhone',
  'AiFillShopping',
  'AiFillStar',
  'AiFillTool',
  'AiOutlineCar',
  'AiOutlineDesktop',
  'AiOutlineGift',
  'AiOutlineSkin',
  'FaPizzaSlice',
  'AiFillHome',
  'HiLightBulb',
  'HiLocationMarker',
]
